apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: tanzu-workshop-example
spec:
  title: Workshop Example
  description: A workshop example created for Tanzu Learning Center
  vendor: mckesson.com
  difficulty: beginner
  duration: 15m
  url: https://github.com/mckesson/tanzu-workshop-example
  content:
    #image: mck-tech-platform-srvs.jfrog.io/tanzu-workshop-example:main
    files: github.com/mckesson/tanzu-workshop-example
  session:
    namespaces:
      budget: small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
