apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: tanzu-workshop-example
spec:
  title: Workshop Example
  description: A workshop example created for Tanzu Learning Center
  vendor: mckesson.com
  difficulty: beginner
  duration: 15m
  url: https://github.com/mckesson/tanzu-workshop-example
  content:
    #image: mck-tech-platform-srvs.jfrog.io/tanzu-workshop-example:main
    files: github.com/mckesson/tanzu-workshop-example?ref=main
  session:
    namespaces:
      budget: medium
      role: edit
    applications:
      terminal:
        enabled: true
        # layout: default
      console:
        enabled: false
      editor:
        enabled: false
